# Generated by Django 4.1.2 on 2022-11-02 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_items_data_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_data',
            name='Timing',
        ),
    ]
