# Generated by Django 4.1.2 on 2022-11-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.AddField(
            model_name='items_data',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
