# Generated by Django 4.1.2 on 2022-11-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_signup_items_data_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items_data',
            old_name='time',
            new_name='timing',
        ),
    ]
