# Generated by Django 4.1.2 on 2022-11-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_time_items_data_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='it',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=30)),
                ('cost', models.CharField(max_length=30)),
                ('timing', models.DateTimeField(auto_now_add=True, null=True)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
