# Generated by Django 4.1.2 on 2022-11-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_it'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='it',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='it',
            name='upload',
        ),
    ]
