# Generated by Django 4.1.2 on 2022-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_it_timing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='it',
        ),
        migrations.AlterField(
            model_name='items_data',
            name='timing',
            field=models.DateTimeField(),
        ),
    ]
