# Generated by Django 4.1.2 on 2022-11-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_delete_it_alter_items_data_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_data',
            name='Current_Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
