# Generated by Django 4.1.2 on 2022-11-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_items_data_top_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_data',
            name='Current_Time',
            field=models.DateTimeField(blank=True, default='2022-11-06 19:51:57 IST+0530'),
        ),
    ]
