# Generated by Django 4.1.2 on 2022-11-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_items_data_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_data',
            name='timing',
            field=models.DateTimeField(blank=True),
        ),
    ]
