# Generated by Django 4.1.2 on 2022-11-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_items_data_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_data',
            name='timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
