# Generated by Django 4.1.2 on 2022-11-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_items_data_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_data',
            name='Description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='items_data',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
