# Generated by Django 4.1.2 on 2022-11-12 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_items_data_description_alter_items_data_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items_data',
            old_name='cost',
            new_name='Cost',
        ),
        migrations.RenameField(
            model_name='items_data',
            old_name='i_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='items_data',
            old_name='upload',
            new_name='Upload',
        ),
    ]
